### ISSUE TITLE
[question] Change the text color and put it at the end of the block

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#35] opened 2019-03-30 04:41 UTC
Hello.

Is there any trick to customize a text color and put it at the end of a block? For example, something like `@color(red @bold(Warning:) blah blah blah.)` or `@color(#ff0000 @bold(Warning:) blah blah blah.)` would generates a bold red text after a `@returns` element. Another way which should work, would:

```
    { Some description.
      @param(ASomeParam[in] Some param.)
      @returns(@True if bla bla bla.)
      <span style="color:green;"><b>NOTE:</b></span> Some relevant note.
      <span style="color:red;"><b>WARNING:</b></span> Some important warning. }
    function Foo(const ASomeParam: string): Boolean;
```

that would generate (image produced by [GIMP](https://www.gimp.org)):

![image](https://user-images.githubusercontent.com/1456829/55271589-e78aa400-528d-11e9-9af3-342f4b888668.png)

Thank you!

**Comment by michaliskambi** [comment] 2019-03-30 09:23
Right now you can only use `@html` tag to achieve this, like

```
@html(<span style=...>) @bold(NOTE:) @html(</span>)
```

**Comment by silvioprog** [comment] 2019-03-30 20:25
Thanks for sharing this trick. :-)

Unfortunately "**NOTE:**" the tag was put in the same line of the description, but I'm going to check some CSS to put it at the bottom of the doc block ... :-)

**Comment by Fr0sT-Brutal** [comment] 2019-11-22 11:30
I guess the issue is solved, so closing it. Please reopen if you have any amendments

**Closed by Fr0sT-Brutal** 2019-11-22 11:30 UTC
