### ISSUE TITLE
Errors in the source code parser and in the HTML generator

### ISSUE THREAD

**Issue by gskoczylas** [pasdoc/pasdoc#188] opened 2023-11-12 19:06 UTC
I have a library written in Delphi that I have used for many years in various of my projects. I have PasDoc comments for most of the code in this library. Today I decided to download the latest version of PasDoc and generate new and better code documentation. From https://pasdoc.github.io/ I downloaded PasDoc 64-bit for Windows.

I want to create documentation in HTML format. Unfortunately, several issues have arisen.

1. PasDoc signals an exception during parsing of the `*.inc` files is UTF-8 encoded with BOM. Processing is disturbed by the BOM. In `*.pas` files, the BOM does not trouble it.
2. When analysing the source files, after `Expanding descriptions (pass 2) ...` phase, the program raises an exception `Access violation`.

I downloaded the latest PasDoc source code from GitHub and tried to find this error. I discovered that the exception is raised in the `PasDoc_Gen` file, in the `TDocGenerator.SearchLink` method. The following code snippet is in this function.

``` pascal
  if Length(NameParts) = 2 then
  begin
	SetLength(NameParts, 1);
	FoundItem := FindGlobal(NameParts);
	Result := MakeItemLink(FoundItem, FoundItem.Name, lcNormal) +
				'.' + Result;
  end;
```

For some reason that I do not yet understand, the `FindGlobal` function sometimes does return **nil**. Then in the next instruction there is an `Access violation` error in the `FoundItem.Name` expression.

**Comment by michaliskambi** [comment] 2023-11-12 21:19
Hi!

AD 1 - This looks like an issue we solved some time ago in PasDoc version on GitHub. That version is not released yet, i.e. the downloads linked from the top of https://pasdoc.github.io/ don't contain the fix yet.

  Please check the "snapshot" version of PasDoc, from https://pasdoc.github.io/DevelopmentSnapshots , and see if the issue is fixed then for you.

  We naturally want to release a new version of PasDoc with these fixes. I planned to do this release already a few months ago... but I failed due to having too much tasks + too little time in all my projects :) But I should get to it eventually.

  If the problem persists even when using that version from snapshots, please submit a testcase -- minimal set of files to reproduce the problem.

AD 2 - Thanks for investigating. I see that code is not ready for `FindGlobal` returning `nil`, and that's already an error -- `FindGlobal` can return `nil`, all code should be prepared for it.

  I fixed it now, by adding extra checks and warning when it happens. Instead of a crash, you should now get a warning like this:

  ```
  Could not resolve link "%s" (from description of "%s"), necessary because LinkLook=llFull and original link was to "%s"
  ```

  Please give Jenkins a few hours to build the latest version of PasDoc, and then check out the snapshots version from https://pasdoc.github.io/DevelopmentSnapshots -- it should have the fix.

  I will appreciate if you can still follow-up this with exact testcase showing when this warning can occur. We shall see can we do something better (to even avoid this warning `Could not resolve link..., necessary because LinkLook=llFull...`). But in any case, it should now be just a warning, not `Access violation`.

  Also please confirm do you use PasDoc with `--link-look=full` option ( https://pasdoc.github.io/LinkLookOption ). Looking at code, the problem was only possible in this case.

**Comment by gskoczylas** [comment] 2023-11-13 00:17
Ad 2. I spent a couple of hours trying to find and understand this error, It is possible that I have made a mistake, but I have the impression that it is not that simple. This error means that some `@link` tag is pointing to a non-existent target. In such a situation, PasDoc displays warnings but does not abandon the work.

This message indicates a target which PasDoc did not find, but does not indicate in which file the erroneous tag is located. Because I couldn't find it, so I decided to find the problematic source file. I copied all the `*.pas` files to another folder and started restoring them one at a time. After restoring each file, I checked whether this error would occur.

At some point, after restoring another `*.pas` file, this error occurred. In most `*.pas` files I have PasDoc comments, but in this latest file there has not yet been a single such comment. 

In addition, I searched all the files to see if the text `@link(ProblematicLink)` occurs anywhere. I did not find it.


I will check the latest snapshot or compile the source code downloaded from GitHub.

**Comment by gskoczylas** [comment] 2023-11-13 20:49
I downloaded the current source code from Git and compiled it (in Delphi 11.3). My first impression is that **PasDoc now works properly**.

Thank you for your quick response.
I tried to correct this myself, but — unfortunately — I was not successful.

**Comment by gskoczylas** [comment] 2023-11-14 19:20
I downloaded the latest version of the source code and compiled it (Delphi 11.3). PasDoc now generates the documentation files. The process runs to completion.

I have reviewed the log generated by PasDoc. I see a lot of false messages about missing targets for the @Link tag. It seems to me that PasDoc does not deal well with source files with a dot in the name. In my library, almost all files have names such as, for example, "MyLibrary.Tokens", "MyLibrary.Log", "MyLibrary.StrUtils" etc.

In doing so, I have noticed that this list of false messages is often different when all the source files are available. And different when I remove all the '*.pas' files from the folder and leave only one of these files for analysis.

If I can find some spare time, I will try to prepare a small test set.

**Comment by michaliskambi** [comment] 2023-11-16 00:09
Thanks for the response. I understand that both AD 1 and AD 2 are now solved, so I'm closing this issue.

It is indeed likely that our `@link` processing (esp. with `--link-look=full` option) isn't correct when using units with dots in their names. If you can, please submit a testcase (as a new bugreport) -- complete set of files to test, and please also send the exact command-line to reproduce the bug (or the `.pds` file if you use GUI, https://pasdoc.github.io/PasDocGui ).

**Closed** 2023-11-16 00:09 UTC
